service: capacityScaler
provider:
  name: aws
  stage: dev
  runtime: python3.6
  region: ap-northeast-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "dynamodb:*"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "cloudwatch:*"
      Resource: "*"
functions:
 Scaler:
    handler: capacityScaler.run
    memorySize: 128
    timeout: 60
plugins:
  - serverless-python-requirements
